name: Firebase Connection Test
on:
  push:
    branches:
      - dev
jobs:
  test_firebase_connection:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ”¥ Ø§Ù„ØªØ­Ù‚Ù‚ Ù…Ù† Ø§Ù„ÙƒÙˆØ¯
        uses: actions/checkout@v4

      - name: ğŸ”¥ ØªØ«Ø¨ÙŠØª Firebase CLI
        run: |
          curl -sL https://firebase.tools | bash
          firebase --version

      - name: ğŸ”‘ ØªØ³Ø¬ÙŠÙ„ Ø§Ù„Ø¯Ø®ÙˆÙ„ Ø¥Ù„Ù‰ Firebase
        run: |
          echo '${{ secrets.CREDENTIAL_FILE_CONTENT }}' > firebase-credentials.json
          export GOOGLE_APPLICATION_CREDENTIALS=firebase-credentials.json
          firebase projects:list

      - name: ğŸ“± Ø§Ø®ØªØ¨Ø§Ø± Ø§Ù„Ø§ØªØµØ§Ù„ Ø¨ØªØ·Ø¨ÙŠÙ‚ Android ÙÙŠ Firebase
        run: |
          firebase apps:list --project=${{ secrets.FIREBASE_PROJECT_ID }}

      - name: ğŸš€ Ø§Ø®ØªØ¨Ø§Ø± Ø§Ù„ÙˆØµÙˆÙ„ Ø¥Ù„Ù‰ Firebase App Distribution
        run: |
          firebase appdistribution:testers:list --app=${{ secrets.FIREBASE_APP_ID }}
